// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2025-03-09 23:53:07.5974468 +0100 CET m=+0.008920801

package itereither

import (
	"github.com/IBM/fp-go/v2/tuple"
)

// SequenceT1 converts 1 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func SequenceT1[E, T1 any](
	t1 SeqEither[E, T1],
) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceSeqT1 converts 1 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func SequenceSeqT1[E, T1 any](
	t1 SeqEither[E, T1],
) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceParT1 converts 1 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func SequenceParT1[E, T1 any](
	t1 SeqEither[E, T1],
) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple1 converts a [tuple.Tuple1[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func SequenceTuple1[E, T1 any](t tuple.Tuple1[SeqEither[E, T1]]) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceSeqTuple1 converts a [tuple.Tuple1[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func SequenceSeqTuple1[E, T1 any](t tuple.Tuple1[SeqEither[E, T1]]) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceParTuple1 converts a [tuple.Tuple1[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func SequenceParTuple1[E, T1 any](t tuple.Tuple1[SeqEither[E, T1]]) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple1 converts a [tuple.Tuple1[A1]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func TraverseTuple1[E error, F1 ~func(A1) SeqEither[E, T1], T1, A1 any](f1 F1) func(tuple.Tuple1[A1]) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseSeqTuple1 converts a [tuple.Tuple1[A1]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func TraverseSeqTuple1[E error, F1 ~func(A1) SeqEither[E, T1], T1, A1 any](f1 F1) func(tuple.Tuple1[A1]) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseParTuple1 converts a [tuple.Tuple1[A1]] into a [SeqEither[E, tuple.Tuple1[T1]]]
func TraverseParTuple1[E error, F1 ~func(A1) SeqEither[E, T1], T1, A1 any](f1 F1) func(tuple.Tuple1[A1]) SeqEither[E, tuple.Tuple1[T1]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT2 converts 2 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple2[T1, T2]]]
func SequenceT2[E, T1, T2 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
) SeqEither[E, tuple.Tuple2[T1, T2]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple2 converts a [tuple.Tuple2[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple2[T1, T2]]]
func SequenceTuple2[E, T1, T2 any](t tuple.Tuple2[SeqEither[E, T1], SeqEither[E, T2]]) SeqEither[E, tuple.Tuple2[T1, T2]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple2 converts a [tuple.Tuple2[A1, A2]] into a [SeqEither[E, tuple.Tuple2[T1, T2]]]
func TraverseTuple2[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], T1, T2, A1, A2 any](f1 F1, f2 F2) func(tuple.Tuple2[A1, A2]) SeqEither[E, tuple.Tuple2[T1, T2]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT3 converts 3 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple3[T1, T2, T3]]]
func SequenceT3[E, T1, T2, T3 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
	t3 SeqEither[E, T3],
) SeqEither[E, tuple.Tuple3[T1, T2, T3]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple3 converts a [tuple.Tuple3[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple3[T1, T2, T3]]]
func SequenceTuple3[E, T1, T2, T3 any](t tuple.Tuple3[SeqEither[E, T1], SeqEither[E, T2], SeqEither[E, T3]]) SeqEither[E, tuple.Tuple3[T1, T2, T3]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple3 converts a [tuple.Tuple3[A1, A2, A3]] into a [SeqEither[E, tuple.Tuple3[T1, T2, T3]]]
func TraverseTuple3[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], F3 ~func(A3) SeqEither[E, T3], T1, T2, T3, A1, A2, A3 any](f1 F1, f2 F2, f3 F3) func(tuple.Tuple3[A1, A2, A3]) SeqEither[E, tuple.Tuple3[T1, T2, T3]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT4 converts 4 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple4[T1, T2, T3, T4]]]
func SequenceT4[E, T1, T2, T3, T4 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
	t3 SeqEither[E, T3],
	t4 SeqEither[E, T4],
) SeqEither[E, tuple.Tuple4[T1, T2, T3, T4]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple4 converts a [tuple.Tuple4[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple4[T1, T2, T3, T4]]]
func SequenceTuple4[E, T1, T2, T3, T4 any](t tuple.Tuple4[SeqEither[E, T1], SeqEither[E, T2], SeqEither[E, T3], SeqEither[E, T4]]) SeqEither[E, tuple.Tuple4[T1, T2, T3, T4]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple4 converts a [tuple.Tuple4[A1, A2, A3, A4]] into a [SeqEither[E, tuple.Tuple4[T1, T2, T3, T4]]]
func TraverseTuple4[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], F3 ~func(A3) SeqEither[E, T3], F4 ~func(A4) SeqEither[E, T4], T1, T2, T3, T4, A1, A2, A3, A4 any](f1 F1, f2 F2, f3 F3, f4 F4) func(tuple.Tuple4[A1, A2, A3, A4]) SeqEither[E, tuple.Tuple4[T1, T2, T3, T4]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT5 converts 5 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple5[T1, T2, T3, T4, T5]]]
func SequenceT5[E, T1, T2, T3, T4, T5 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
	t3 SeqEither[E, T3],
	t4 SeqEither[E, T4],
	t5 SeqEither[E, T5],
) SeqEither[E, tuple.Tuple5[T1, T2, T3, T4, T5]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple5 converts a [tuple.Tuple5[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple5[T1, T2, T3, T4, T5]]]
func SequenceTuple5[E, T1, T2, T3, T4, T5 any](t tuple.Tuple5[SeqEither[E, T1], SeqEither[E, T2], SeqEither[E, T3], SeqEither[E, T4], SeqEither[E, T5]]) SeqEither[E, tuple.Tuple5[T1, T2, T3, T4, T5]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple5 converts a [tuple.Tuple5[A1, A2, A3, A4, A5]] into a [SeqEither[E, tuple.Tuple5[T1, T2, T3, T4, T5]]]
func TraverseTuple5[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], F3 ~func(A3) SeqEither[E, T3], F4 ~func(A4) SeqEither[E, T4], F5 ~func(A5) SeqEither[E, T5], T1, T2, T3, T4, T5, A1, A2, A3, A4, A5 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5) func(tuple.Tuple5[A1, A2, A3, A4, A5]) SeqEither[E, tuple.Tuple5[T1, T2, T3, T4, T5]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT6 converts 6 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple6[T1, T2, T3, T4, T5, T6]]]
func SequenceT6[E, T1, T2, T3, T4, T5, T6 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
	t3 SeqEither[E, T3],
	t4 SeqEither[E, T4],
	t5 SeqEither[E, T5],
	t6 SeqEither[E, T6],
) SeqEither[E, tuple.Tuple6[T1, T2, T3, T4, T5, T6]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple6 converts a [tuple.Tuple6[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple6[T1, T2, T3, T4, T5, T6]]]
func SequenceTuple6[E, T1, T2, T3, T4, T5, T6 any](t tuple.Tuple6[SeqEither[E, T1], SeqEither[E, T2], SeqEither[E, T3], SeqEither[E, T4], SeqEither[E, T5], SeqEither[E, T6]]) SeqEither[E, tuple.Tuple6[T1, T2, T3, T4, T5, T6]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple6 converts a [tuple.Tuple6[A1, A2, A3, A4, A5, A6]] into a [SeqEither[E, tuple.Tuple6[T1, T2, T3, T4, T5, T6]]]
func TraverseTuple6[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], F3 ~func(A3) SeqEither[E, T3], F4 ~func(A4) SeqEither[E, T4], F5 ~func(A5) SeqEither[E, T5], F6 ~func(A6) SeqEither[E, T6], T1, T2, T3, T4, T5, T6, A1, A2, A3, A4, A5, A6 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6) func(tuple.Tuple6[A1, A2, A3, A4, A5, A6]) SeqEither[E, tuple.Tuple6[T1, T2, T3, T4, T5, T6]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT7 converts 7 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple7[T1, T2, T3, T4, T5, T6, T7]]]
func SequenceT7[E, T1, T2, T3, T4, T5, T6, T7 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
	t3 SeqEither[E, T3],
	t4 SeqEither[E, T4],
	t5 SeqEither[E, T5],
	t6 SeqEither[E, T6],
	t7 SeqEither[E, T7],
) SeqEither[E, tuple.Tuple7[T1, T2, T3, T4, T5, T6, T7]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple7 converts a [tuple.Tuple7[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple7[T1, T2, T3, T4, T5, T6, T7]]]
func SequenceTuple7[E, T1, T2, T3, T4, T5, T6, T7 any](t tuple.Tuple7[SeqEither[E, T1], SeqEither[E, T2], SeqEither[E, T3], SeqEither[E, T4], SeqEither[E, T5], SeqEither[E, T6], SeqEither[E, T7]]) SeqEither[E, tuple.Tuple7[T1, T2, T3, T4, T5, T6, T7]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple7 converts a [tuple.Tuple7[A1, A2, A3, A4, A5, A6, A7]] into a [SeqEither[E, tuple.Tuple7[T1, T2, T3, T4, T5, T6, T7]]]
func TraverseTuple7[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], F3 ~func(A3) SeqEither[E, T3], F4 ~func(A4) SeqEither[E, T4], F5 ~func(A5) SeqEither[E, T5], F6 ~func(A6) SeqEither[E, T6], F7 ~func(A7) SeqEither[E, T7], T1, T2, T3, T4, T5, T6, T7, A1, A2, A3, A4, A5, A6, A7 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6, f7 F7) func(tuple.Tuple7[A1, A2, A3, A4, A5, A6, A7]) SeqEither[E, tuple.Tuple7[T1, T2, T3, T4, T5, T6, T7]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT8 converts 8 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]]]
func SequenceT8[E, T1, T2, T3, T4, T5, T6, T7, T8 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
	t3 SeqEither[E, T3],
	t4 SeqEither[E, T4],
	t5 SeqEither[E, T5],
	t6 SeqEither[E, T6],
	t7 SeqEither[E, T7],
	t8 SeqEither[E, T8],
) SeqEither[E, tuple.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple8 converts a [tuple.Tuple8[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]]]
func SequenceTuple8[E, T1, T2, T3, T4, T5, T6, T7, T8 any](t tuple.Tuple8[SeqEither[E, T1], SeqEither[E, T2], SeqEither[E, T3], SeqEither[E, T4], SeqEither[E, T5], SeqEither[E, T6], SeqEither[E, T7], SeqEither[E, T8]]) SeqEither[E, tuple.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple8 converts a [tuple.Tuple8[A1, A2, A3, A4, A5, A6, A7, A8]] into a [SeqEither[E, tuple.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]]]
func TraverseTuple8[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], F3 ~func(A3) SeqEither[E, T3], F4 ~func(A4) SeqEither[E, T4], F5 ~func(A5) SeqEither[E, T5], F6 ~func(A6) SeqEither[E, T6], F7 ~func(A7) SeqEither[E, T7], F8 ~func(A8) SeqEither[E, T8], T1, T2, T3, T4, T5, T6, T7, T8, A1, A2, A3, A4, A5, A6, A7, A8 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6, f7 F7, f8 F8) func(tuple.Tuple8[A1, A2, A3, A4, A5, A6, A7, A8]) SeqEither[E, tuple.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT9 converts 9 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]]]
func SequenceT9[E, T1, T2, T3, T4, T5, T6, T7, T8, T9 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
	t3 SeqEither[E, T3],
	t4 SeqEither[E, T4],
	t5 SeqEither[E, T5],
	t6 SeqEither[E, T6],
	t7 SeqEither[E, T7],
	t8 SeqEither[E, T8],
	t9 SeqEither[E, T9],
) SeqEither[E, tuple.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple9 converts a [tuple.Tuple9[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]]]
func SequenceTuple9[E, T1, T2, T3, T4, T5, T6, T7, T8, T9 any](t tuple.Tuple9[SeqEither[E, T1], SeqEither[E, T2], SeqEither[E, T3], SeqEither[E, T4], SeqEither[E, T5], SeqEither[E, T6], SeqEither[E, T7], SeqEither[E, T8], SeqEither[E, T9]]) SeqEither[E, tuple.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple9 converts a [tuple.Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9]] into a [SeqEither[E, tuple.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]]]
func TraverseTuple9[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], F3 ~func(A3) SeqEither[E, T3], F4 ~func(A4) SeqEither[E, T4], F5 ~func(A5) SeqEither[E, T5], F6 ~func(A6) SeqEither[E, T6], F7 ~func(A7) SeqEither[E, T7], F8 ~func(A8) SeqEither[E, T8], F9 ~func(A9) SeqEither[E, T9], T1, T2, T3, T4, T5, T6, T7, T8, T9, A1, A2, A3, A4, A5, A6, A7, A8, A9 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6, f7 F7, f8 F8, f9 F9) func(tuple.Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9]) SeqEither[E, tuple.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT10 converts 10 [SeqEither[E, T]] into a [SeqEither[E, tuple.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]]]
func SequenceT10[E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any](
	t1 SeqEither[E, T1],
	t2 SeqEither[E, T2],
	t3 SeqEither[E, T3],
	t4 SeqEither[E, T4],
	t5 SeqEither[E, T5],
	t6 SeqEither[E, T6],
	t7 SeqEither[E, T7],
	t8 SeqEither[E, T8],
	t9 SeqEither[E, T9],
	t10 SeqEither[E, T10],
) SeqEither[E, tuple.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]] {
	_ = "STUB: not implemented"
	return nil
}

// SequenceTuple10 converts a [tuple.Tuple10[SeqEither[E, T]]] into a [SeqEither[E, tuple.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]]]
func SequenceTuple10[E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any](t tuple.Tuple10[SeqEither[E, T1], SeqEither[E, T2], SeqEither[E, T3], SeqEither[E, T4], SeqEither[E, T5], SeqEither[E, T6], SeqEither[E, T7], SeqEither[E, T8], SeqEither[E, T9], SeqEither[E, T10]]) SeqEither[E, tuple.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]] {
	_ = "STUB: not implemented"
	return nil
}

// TraverseTuple10 converts a [tuple.Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]] into a [SeqEither[E, tuple.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]]]
func TraverseTuple10[E error, F1 ~func(A1) SeqEither[E, T1], F2 ~func(A2) SeqEither[E, T2], F3 ~func(A3) SeqEither[E, T3], F4 ~func(A4) SeqEither[E, T4], F5 ~func(A5) SeqEither[E, T5], F6 ~func(A6) SeqEither[E, T6], F7 ~func(A7) SeqEither[E, T7], F8 ~func(A8) SeqEither[E, T8], F9 ~func(A9) SeqEither[E, T9], F10 ~func(A10) SeqEither[E, T10], T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6, f7 F7, f8 F8, f9 F9, f10 F10) func(tuple.Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]) SeqEither[E, tuple.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]] {
	_ = "STUB: not implemented"
	return nil
}
