package lens

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2026-01-29 10:07:27.7545248 +0100 CET m=+0.002646001

import (
	__lens "github.com/IBM/fp-go/v2/optics/lens"
	__lens_option "github.com/IBM/fp-go/v2/optics/lens/option"
	option "github.com/IBM/fp-go/v2/optics/lens/option"
	__prism "github.com/IBM/fp-go/v2/optics/prism"
)

// PersonLenses provides [lenses] for accessing fields of [Person]
//
// [lenses]: __lens.Lens
type PersonLenses struct {
	// mandatory fields
	Name  __lens.Lens[Person, string]
	Age   __lens.Lens[Person, int]
	Email __lens.Lens[Person, string]
	Phone __lens.Lens[Person, *string]
	// optional fields
	NameO  __lens_option.LensO[Person, string]
	AgeO   __lens_option.LensO[Person, int]
	EmailO __lens_option.LensO[Person, string]
	PhoneO __lens_option.LensO[Person, *string]
}

// PersonRefLenses provides [lenses] for accessing fields of [Person] via a reference to [Person]
//
// [lenses]: __lens.Lens
type PersonRefLenses struct {
	// mandatory fields
	Name  __lens.Lens[*Person, string]
	Age   __lens.Lens[*Person, int]
	Email __lens.Lens[*Person, string]
	Phone __lens.Lens[*Person, *string]
	// optional fields
	NameO  __lens_option.LensO[*Person, string]
	AgeO   __lens_option.LensO[*Person, int]
	EmailO __lens_option.LensO[*Person, string]
	PhoneO __lens_option.LensO[*Person, *string]
}

// PersonPrisms provides [prisms] for accessing fields of [Person]
//
// [prisms]: __prism.Prism
type PersonPrisms struct {
	Name  __prism.Prism[Person, string]
	Age   __prism.Prism[Person, int]
	Email __prism.Prism[Person, string]
	Phone __prism.Prism[Person, *string]
}

// PersonRefPrisms provides [prisms] for accessing fields of [Person] via a reference to [Person]
//
// [prisms]: __prism.Prism
type PersonRefPrisms struct {
	Name  __prism.Prism[*Person, string]
	Age   __prism.Prism[*Person, int]
	Email __prism.Prism[*Person, string]
	Phone __prism.Prism[*Person, *string]
}

// MakePersonLenses creates a new [PersonLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakePersonLenses() PersonLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(PersonLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakePersonRefLenses creates a new [PersonRefLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakePersonRefLenses() PersonRefLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(PersonRefLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakePersonPrisms creates a new [PersonPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakePersonPrisms() PersonPrisms { _ = "STUB: not implemented"; return *new(PersonPrisms) }

// MakePersonRefPrisms creates a new [PersonRefPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakePersonRefPrisms() PersonRefPrisms { _ = "STUB: not implemented"; return *new(PersonRefPrisms) }

// AddressLenses provides [lenses] for accessing fields of [Address]
//
// [lenses]: __lens.Lens
type AddressLenses struct {
	// mandatory fields
	Street  __lens.Lens[Address, string]
	City    __lens.Lens[Address, string]
	ZipCode __lens.Lens[Address, string]
	Country __lens.Lens[Address, string]
	State   __lens.Lens[Address, *string]
	// optional fields
	StreetO  __lens_option.LensO[Address, string]
	CityO    __lens_option.LensO[Address, string]
	ZipCodeO __lens_option.LensO[Address, string]
	CountryO __lens_option.LensO[Address, string]
	StateO   __lens_option.LensO[Address, *string]
}

// AddressRefLenses provides [lenses] for accessing fields of [Address] via a reference to [Address]
//
// [lenses]: __lens.Lens
type AddressRefLenses struct {
	// mandatory fields
	Street  __lens.Lens[*Address, string]
	City    __lens.Lens[*Address, string]
	ZipCode __lens.Lens[*Address, string]
	Country __lens.Lens[*Address, string]
	State   __lens.Lens[*Address, *string]
	// optional fields
	StreetO  __lens_option.LensO[*Address, string]
	CityO    __lens_option.LensO[*Address, string]
	ZipCodeO __lens_option.LensO[*Address, string]
	CountryO __lens_option.LensO[*Address, string]
	StateO   __lens_option.LensO[*Address, *string]
}

// AddressPrisms provides [prisms] for accessing fields of [Address]
//
// [prisms]: __prism.Prism
type AddressPrisms struct {
	Street  __prism.Prism[Address, string]
	City    __prism.Prism[Address, string]
	ZipCode __prism.Prism[Address, string]
	Country __prism.Prism[Address, string]
	State   __prism.Prism[Address, *string]
}

// AddressRefPrisms provides [prisms] for accessing fields of [Address] via a reference to [Address]
//
// [prisms]: __prism.Prism
type AddressRefPrisms struct {
	Street  __prism.Prism[*Address, string]
	City    __prism.Prism[*Address, string]
	ZipCode __prism.Prism[*Address, string]
	Country __prism.Prism[*Address, string]
	State   __prism.Prism[*Address, *string]
}

// MakeAddressLenses creates a new [AddressLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeAddressLenses() AddressLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(AddressLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeAddressRefLenses creates a new [AddressRefLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeAddressRefLenses() AddressRefLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(AddressRefLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeAddressPrisms creates a new [AddressPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeAddressPrisms() AddressPrisms { _ = "STUB: not implemented"; return *new(AddressPrisms) }

// MakeAddressRefPrisms creates a new [AddressRefPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeAddressRefPrisms() AddressRefPrisms {
	_ = "STUB: not implemented"
	return *new(AddressRefPrisms)
}

// CompanyLenses provides [lenses] for accessing fields of [Company]
//
// [lenses]: __lens.Lens
type CompanyLenses struct {
	// mandatory fields
	Name    __lens.Lens[Company, string]
	Address __lens.Lens[Company, Address]
	CEO     __lens.Lens[Company, Person]
	Website __lens.Lens[Company, *string]
	// optional fields
	NameO    __lens_option.LensO[Company, string]
	AddressO __lens_option.LensO[Company, Address]
	CEOO     __lens_option.LensO[Company, Person]
	WebsiteO __lens_option.LensO[Company, *string]
}

// CompanyRefLenses provides [lenses] for accessing fields of [Company] via a reference to [Company]
//
// [lenses]: __lens.Lens
type CompanyRefLenses struct {
	// mandatory fields
	Name    __lens.Lens[*Company, string]
	Address __lens.Lens[*Company, Address]
	CEO     __lens.Lens[*Company, Person]
	Website __lens.Lens[*Company, *string]
	// optional fields
	NameO    __lens_option.LensO[*Company, string]
	AddressO __lens_option.LensO[*Company, Address]
	CEOO     __lens_option.LensO[*Company, Person]
	WebsiteO __lens_option.LensO[*Company, *string]
}

// CompanyPrisms provides [prisms] for accessing fields of [Company]
//
// [prisms]: __prism.Prism
type CompanyPrisms struct {
	Name    __prism.Prism[Company, string]
	Address __prism.Prism[Company, Address]
	CEO     __prism.Prism[Company, Person]
	Website __prism.Prism[Company, *string]
}

// CompanyRefPrisms provides [prisms] for accessing fields of [Company] via a reference to [Company]
//
// [prisms]: __prism.Prism
type CompanyRefPrisms struct {
	Name    __prism.Prism[*Company, string]
	Address __prism.Prism[*Company, Address]
	CEO     __prism.Prism[*Company, Person]
	Website __prism.Prism[*Company, *string]
}

// MakeCompanyLenses creates a new [CompanyLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeCompanyLenses() CompanyLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(CompanyLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeCompanyRefLenses creates a new [CompanyRefLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeCompanyRefLenses() CompanyRefLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(CompanyRefLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeCompanyPrisms creates a new [CompanyPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeCompanyPrisms() CompanyPrisms { _ = "STUB: not implemented"; return *new(CompanyPrisms) }

// MakeCompanyRefPrisms creates a new [CompanyRefPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeCompanyRefPrisms() CompanyRefPrisms {
	_ = "STUB: not implemented"
	return *new(CompanyRefPrisms)
}

// CompanyExtendedLenses provides [lenses] for accessing fields of [CompanyExtended]
//
// [lenses]: __lens.Lens
type CompanyExtendedLenses struct {
	// mandatory fields
	Name     __lens.Lens[CompanyExtended, string]
	Address  __lens.Lens[CompanyExtended, Address]
	CEO      __lens.Lens[CompanyExtended, Person]
	Website  __lens.Lens[CompanyExtended, *string]
	Extended __lens.Lens[CompanyExtended, string]
	// optional fields
	NameO     __lens_option.LensO[CompanyExtended, string]
	AddressO  __lens_option.LensO[CompanyExtended, Address]
	CEOO      __lens_option.LensO[CompanyExtended, Person]
	WebsiteO  __lens_option.LensO[CompanyExtended, *string]
	ExtendedO __lens_option.LensO[CompanyExtended, string]
}

// CompanyExtendedRefLenses provides [lenses] for accessing fields of [CompanyExtended] via a reference to [CompanyExtended]
//
// [lenses]: __lens.Lens
type CompanyExtendedRefLenses struct {
	// mandatory fields
	Name     __lens.Lens[*CompanyExtended, string]
	Address  __lens.Lens[*CompanyExtended, Address]
	CEO      __lens.Lens[*CompanyExtended, Person]
	Website  __lens.Lens[*CompanyExtended, *string]
	Extended __lens.Lens[*CompanyExtended, string]
	// optional fields
	NameO     __lens_option.LensO[*CompanyExtended, string]
	AddressO  __lens_option.LensO[*CompanyExtended, Address]
	CEOO      __lens_option.LensO[*CompanyExtended, Person]
	WebsiteO  __lens_option.LensO[*CompanyExtended, *string]
	ExtendedO __lens_option.LensO[*CompanyExtended, string]
}

// CompanyExtendedPrisms provides [prisms] for accessing fields of [CompanyExtended]
//
// [prisms]: __prism.Prism
type CompanyExtendedPrisms struct {
	Name     __prism.Prism[CompanyExtended, string]
	Address  __prism.Prism[CompanyExtended, Address]
	CEO      __prism.Prism[CompanyExtended, Person]
	Website  __prism.Prism[CompanyExtended, *string]
	Extended __prism.Prism[CompanyExtended, string]
}

// CompanyExtendedRefPrisms provides [prisms] for accessing fields of [CompanyExtended] via a reference to [CompanyExtended]
//
// [prisms]: __prism.Prism
type CompanyExtendedRefPrisms struct {
	Name     __prism.Prism[*CompanyExtended, string]
	Address  __prism.Prism[*CompanyExtended, Address]
	CEO      __prism.Prism[*CompanyExtended, Person]
	Website  __prism.Prism[*CompanyExtended, *string]
	Extended __prism.Prism[*CompanyExtended, string]
}

// MakeCompanyExtendedLenses creates a new [CompanyExtendedLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeCompanyExtendedLenses() CompanyExtendedLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(CompanyExtendedLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeCompanyExtendedRefLenses creates a new [CompanyExtendedRefLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeCompanyExtendedRefLenses() CompanyExtendedRefLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(CompanyExtendedRefLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeCompanyExtendedPrisms creates a new [CompanyExtendedPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeCompanyExtendedPrisms() CompanyExtendedPrisms {
	_ = "STUB: not implemented"
	return *new(CompanyExtendedPrisms)
}

// MakeCompanyExtendedRefPrisms creates a new [CompanyExtendedRefPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeCompanyExtendedRefPrisms() CompanyExtendedRefPrisms {
	_ = "STUB: not implemented"
	return *new(CompanyExtendedRefPrisms)
}

// CheckOptionLenses provides [lenses] for accessing fields of [CheckOption]
//
// [lenses]: __lens.Lens
type CheckOptionLenses struct {
	// mandatory fields
	Name  __lens.Lens[CheckOption, option.Option[string]]
	Value __lens.Lens[CheckOption, string]
	// optional fields
	ValueO __lens_option.LensO[CheckOption, string]
}

// CheckOptionRefLenses provides [lenses] for accessing fields of [CheckOption] via a reference to [CheckOption]
//
// [lenses]: __lens.Lens
type CheckOptionRefLenses struct {
	// mandatory fields
	Name  __lens.Lens[*CheckOption, option.Option[string]]
	Value __lens.Lens[*CheckOption, string]
	// optional fields
	ValueO __lens_option.LensO[*CheckOption, string]
}

// CheckOptionPrisms provides [prisms] for accessing fields of [CheckOption]
//
// [prisms]: __prism.Prism
type CheckOptionPrisms struct {
	Name  __prism.Prism[CheckOption, option.Option[string]]
	Value __prism.Prism[CheckOption, string]
}

// CheckOptionRefPrisms provides [prisms] for accessing fields of [CheckOption] via a reference to [CheckOption]
//
// [prisms]: __prism.Prism
type CheckOptionRefPrisms struct {
	Name  __prism.Prism[*CheckOption, option.Option[string]]
	Value __prism.Prism[*CheckOption, string]
}

// MakeCheckOptionLenses creates a new [CheckOptionLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeCheckOptionLenses() CheckOptionLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(CheckOptionLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeCheckOptionRefLenses creates a new [CheckOptionRefLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeCheckOptionRefLenses() CheckOptionRefLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(CheckOptionRefLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeCheckOptionPrisms creates a new [CheckOptionPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeCheckOptionPrisms() CheckOptionPrisms {
	_ = "STUB: not implemented"
	return *new(CheckOptionPrisms)
}

// MakeCheckOptionRefPrisms creates a new [CheckOptionRefPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeCheckOptionRefPrisms() CheckOptionRefPrisms {
	_ = "STUB: not implemented"
	return *new(CheckOptionRefPrisms)
}

// WithGenericLenses provides [lenses] for accessing fields of [WithGeneric]
//
// [lenses]: __lens.Lens
type WithGenericLenses[T any] struct {
	// mandatory fields
	Name  __lens.Lens[WithGeneric[T], string]
	Value __lens.Lens[WithGeneric[T], T]
	// optional fields
	NameO __lens_option.LensO[WithGeneric[T], string]
}

// WithGenericRefLenses provides [lenses] for accessing fields of [WithGeneric] via a reference to [WithGeneric]
//
// [lenses]: __lens.Lens
type WithGenericRefLenses[T any] struct {
	// mandatory fields
	Name  __lens.Lens[*WithGeneric[T], string]
	Value __lens.Lens[*WithGeneric[T], T]
	// optional fields
	NameO __lens_option.LensO[*WithGeneric[T], string]
}

// WithGenericPrisms provides [prisms] for accessing fields of [WithGeneric]
//
// [prisms]: __prism.Prism
type WithGenericPrisms[T any] struct {
	Name  __prism.Prism[WithGeneric[T], string]
	Value __prism.Prism[WithGeneric[T], T]
}

// WithGenericRefPrisms provides [prisms] for accessing fields of [WithGeneric] via a reference to [WithGeneric]
//
// [prisms]: __prism.Prism
type WithGenericRefPrisms[T any] struct {
	Name  __prism.Prism[*WithGeneric[T], string]
	Value __prism.Prism[*WithGeneric[T], T]
}

// MakeWithGenericLenses creates a new [WithGenericLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeWithGenericLenses[T any]() WithGenericLenses[T] {
	_ = "STUB: not implemented"
	// mandatory lenses
	return nil
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeWithGenericRefLenses creates a new [WithGenericRefLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeWithGenericRefLenses[T any]() WithGenericRefLenses[T] {
	_ = "STUB: not implemented"
	// mandatory lenses
	return nil
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeWithGenericPrisms creates a new [WithGenericPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeWithGenericPrisms[T any]() WithGenericPrisms[T] { _ = "STUB: not implemented"; return nil }

// MakeWithGenericRefPrisms creates a new [WithGenericRefPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeWithGenericRefPrisms[T any]() WithGenericRefPrisms[T] {
	_ = "STUB: not implemented"
	return nil
}

// DataBuilderLenses provides [lenses] for accessing fields of [DataBuilder]
//
// [lenses]: __lens.Lens
type DataBuilderLenses struct {
	// mandatory fields
	name  __lens.Lens[DataBuilder, string]
	value __lens.Lens[DataBuilder, string]
	// optional fields
	nameO  __lens_option.LensO[DataBuilder, string]
	valueO __lens_option.LensO[DataBuilder, string]
}

// DataBuilderRefLenses provides [lenses] for accessing fields of [DataBuilder] via a reference to [DataBuilder]
//
// [lenses]: __lens.Lens
type DataBuilderRefLenses struct {
	// mandatory fields
	name  __lens.Lens[*DataBuilder, string]
	value __lens.Lens[*DataBuilder, string]
	// optional fields
	nameO  __lens_option.LensO[*DataBuilder, string]
	valueO __lens_option.LensO[*DataBuilder, string]
}

// DataBuilderPrisms provides [prisms] for accessing fields of [DataBuilder]
//
// [prisms]: __prism.Prism
type DataBuilderPrisms struct {
	name  __prism.Prism[DataBuilder, string]
	value __prism.Prism[DataBuilder, string]
}

// DataBuilderRefPrisms provides [prisms] for accessing fields of [DataBuilder] via a reference to [DataBuilder]
//
// [prisms]: __prism.Prism
type DataBuilderRefPrisms struct {
	name  __prism.Prism[*DataBuilder, string]
	value __prism.Prism[*DataBuilder, string]
}

// MakeDataBuilderLenses creates a new [DataBuilderLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeDataBuilderLenses() DataBuilderLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(DataBuilderLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeDataBuilderRefLenses creates a new [DataBuilderRefLenses] with [lenses] for all fields
//
// [lenses]:__lens.Lens
func MakeDataBuilderRefLenses() DataBuilderRefLenses {
	_ = "STUB: not implemented"
	// mandatory lenses
	return *new(DataBuilderRefLenses)
}

// optional lenses

// mandatory lenses

// optional lenses

// MakeDataBuilderPrisms creates a new [DataBuilderPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeDataBuilderPrisms() DataBuilderPrisms {
	_ = "STUB: not implemented"
	return *new(DataBuilderPrisms)
}

// MakeDataBuilderRefPrisms creates a new [DataBuilderRefPrisms] with [prisms] for all fields
//
// [prisms]:__prism.Prism
func MakeDataBuilderRefPrisms() DataBuilderRefPrisms {
	_ = "STUB: not implemented"
	return *new(DataBuilderRefPrisms)
}
