// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2024-02-29 16:19:13.1643755 +0100 CET m=+0.085210801
package generic

import (
	ET "github.com/IBM/fp-go/either"
	T "github.com/IBM/fp-go/tuple"
)

// Eitherize0 converts a function with 0 parameters returning a tuple into a function with 0 parameters returning a [GIOA]
func Eitherize0[GIOA ~func() ET.Either[error, R], F ~func() (R, error), R any](f F) func() GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize0 converts a function with 0 parameters returning a tuple into a function with 0 parameters returning a [GIOA]
func Uneitherize0[GIOA ~func() ET.Either[error, R], GTA ~func() GIOA, R any](f GTA) func() (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize1 converts a function with 1 parameters returning a tuple into a function with 1 parameters returning a [GIOA]
func Eitherize1[GIOA ~func() ET.Either[error, R], F ~func(T1) (R, error), T1, R any](f F) func(T1) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize1 converts a function with 1 parameters returning a tuple into a function with 1 parameters returning a [GIOA]
func Uneitherize1[GIOA ~func() ET.Either[error, R], GTA ~func(T1) GIOA, T1, R any](f GTA) func(T1) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT1 converts 1 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple1[T1]]]
func SequenceT1[
	G_TUPLE1 ~func() ET.Either[E, T.Tuple1[T1]],
	G_T1 ~func() ET.Either[E, T1],
	E, T1 any](
	t1 G_T1,
) G_TUPLE1 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE1)
}

// SequenceTuple1 converts a [T.Tuple1[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple1[T1]]]
func SequenceTuple1[
	G_TUPLE1 ~func() ET.Either[E, T.Tuple1[T1]],
	G_T1 ~func() ET.Either[E, T1],
	E, T1 any](t T.Tuple1[G_T1]) G_TUPLE1 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE1)
}

// TraverseTuple1 converts a [T.Tuple1[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple1[T1]]]
func TraverseTuple1[
	G_TUPLE1 ~func() ET.Either[E, T.Tuple1[T1]],
	F1 ~func(A1) G_T1,
	G_T1 ~func() ET.Either[E, T1],
	E, A1, T1 any](f1 F1) func(T.Tuple1[A1]) G_TUPLE1 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize2 converts a function with 2 parameters returning a tuple into a function with 2 parameters returning a [GIOA]
func Eitherize2[GIOA ~func() ET.Either[error, R], F ~func(T1, T2) (R, error), T1, T2, R any](f F) func(T1, T2) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize2 converts a function with 2 parameters returning a tuple into a function with 2 parameters returning a [GIOA]
func Uneitherize2[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2) GIOA, T1, T2, R any](f GTA) func(T1, T2) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT2 converts 2 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple2[T1, T2]]]
func SequenceT2[
	G_TUPLE2 ~func() ET.Either[E, T.Tuple2[T1, T2]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	E, T1, T2 any](
	t1 G_T1,
	t2 G_T2,
) G_TUPLE2 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE2)
}

// SequenceTuple2 converts a [T.Tuple2[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple2[T1, T2]]]
func SequenceTuple2[
	G_TUPLE2 ~func() ET.Either[E, T.Tuple2[T1, T2]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	E, T1, T2 any](t T.Tuple2[G_T1, G_T2]) G_TUPLE2 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE2)
}

// TraverseTuple2 converts a [T.Tuple2[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple2[T1, T2]]]
func TraverseTuple2[
	G_TUPLE2 ~func() ET.Either[E, T.Tuple2[T1, T2]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	E, A1, A2, T1, T2 any](f1 F1, f2 F2) func(T.Tuple2[A1, A2]) G_TUPLE2 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize3 converts a function with 3 parameters returning a tuple into a function with 3 parameters returning a [GIOA]
func Eitherize3[GIOA ~func() ET.Either[error, R], F ~func(T1, T2, T3) (R, error), T1, T2, T3, R any](f F) func(T1, T2, T3) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize3 converts a function with 3 parameters returning a tuple into a function with 3 parameters returning a [GIOA]
func Uneitherize3[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2, T3) GIOA, T1, T2, T3, R any](f GTA) func(T1, T2, T3) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT3 converts 3 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple3[T1, T2, T3]]]
func SequenceT3[
	G_TUPLE3 ~func() ET.Either[E, T.Tuple3[T1, T2, T3]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	E, T1, T2, T3 any](
	t1 G_T1,
	t2 G_T2,
	t3 G_T3,
) G_TUPLE3 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE3)
}

// SequenceTuple3 converts a [T.Tuple3[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple3[T1, T2, T3]]]
func SequenceTuple3[
	G_TUPLE3 ~func() ET.Either[E, T.Tuple3[T1, T2, T3]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	E, T1, T2, T3 any](t T.Tuple3[G_T1, G_T2, G_T3]) G_TUPLE3 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE3)
}

// TraverseTuple3 converts a [T.Tuple3[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple3[T1, T2, T3]]]
func TraverseTuple3[
	G_TUPLE3 ~func() ET.Either[E, T.Tuple3[T1, T2, T3]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	F3 ~func(A3) G_T3,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	E, A1, A2, A3, T1, T2, T3 any](f1 F1, f2 F2, f3 F3) func(T.Tuple3[A1, A2, A3]) G_TUPLE3 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize4 converts a function with 4 parameters returning a tuple into a function with 4 parameters returning a [GIOA]
func Eitherize4[GIOA ~func() ET.Either[error, R], F ~func(T1, T2, T3, T4) (R, error), T1, T2, T3, T4, R any](f F) func(T1, T2, T3, T4) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize4 converts a function with 4 parameters returning a tuple into a function with 4 parameters returning a [GIOA]
func Uneitherize4[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2, T3, T4) GIOA, T1, T2, T3, T4, R any](f GTA) func(T1, T2, T3, T4) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT4 converts 4 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple4[T1, T2, T3, T4]]]
func SequenceT4[
	G_TUPLE4 ~func() ET.Either[E, T.Tuple4[T1, T2, T3, T4]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	E, T1, T2, T3, T4 any](
	t1 G_T1,
	t2 G_T2,
	t3 G_T3,
	t4 G_T4,
) G_TUPLE4 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE4)
}

// SequenceTuple4 converts a [T.Tuple4[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple4[T1, T2, T3, T4]]]
func SequenceTuple4[
	G_TUPLE4 ~func() ET.Either[E, T.Tuple4[T1, T2, T3, T4]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	E, T1, T2, T3, T4 any](t T.Tuple4[G_T1, G_T2, G_T3, G_T4]) G_TUPLE4 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE4)
}

// TraverseTuple4 converts a [T.Tuple4[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple4[T1, T2, T3, T4]]]
func TraverseTuple4[
	G_TUPLE4 ~func() ET.Either[E, T.Tuple4[T1, T2, T3, T4]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	F3 ~func(A3) G_T3,
	F4 ~func(A4) G_T4,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	E, A1, A2, A3, A4, T1, T2, T3, T4 any](f1 F1, f2 F2, f3 F3, f4 F4) func(T.Tuple4[A1, A2, A3, A4]) G_TUPLE4 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize5 converts a function with 5 parameters returning a tuple into a function with 5 parameters returning a [GIOA]
func Eitherize5[GIOA ~func() ET.Either[error, R], F ~func(T1, T2, T3, T4, T5) (R, error), T1, T2, T3, T4, T5, R any](f F) func(T1, T2, T3, T4, T5) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize5 converts a function with 5 parameters returning a tuple into a function with 5 parameters returning a [GIOA]
func Uneitherize5[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2, T3, T4, T5) GIOA, T1, T2, T3, T4, T5, R any](f GTA) func(T1, T2, T3, T4, T5) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT5 converts 5 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple5[T1, T2, T3, T4, T5]]]
func SequenceT5[
	G_TUPLE5 ~func() ET.Either[E, T.Tuple5[T1, T2, T3, T4, T5]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	E, T1, T2, T3, T4, T5 any](
	t1 G_T1,
	t2 G_T2,
	t3 G_T3,
	t4 G_T4,
	t5 G_T5,
) G_TUPLE5 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE5)
}

// SequenceTuple5 converts a [T.Tuple5[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple5[T1, T2, T3, T4, T5]]]
func SequenceTuple5[
	G_TUPLE5 ~func() ET.Either[E, T.Tuple5[T1, T2, T3, T4, T5]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	E, T1, T2, T3, T4, T5 any](t T.Tuple5[G_T1, G_T2, G_T3, G_T4, G_T5]) G_TUPLE5 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE5)
}

// TraverseTuple5 converts a [T.Tuple5[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple5[T1, T2, T3, T4, T5]]]
func TraverseTuple5[
	G_TUPLE5 ~func() ET.Either[E, T.Tuple5[T1, T2, T3, T4, T5]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	F3 ~func(A3) G_T3,
	F4 ~func(A4) G_T4,
	F5 ~func(A5) G_T5,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	E, A1, A2, A3, A4, A5, T1, T2, T3, T4, T5 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5) func(T.Tuple5[A1, A2, A3, A4, A5]) G_TUPLE5 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize6 converts a function with 6 parameters returning a tuple into a function with 6 parameters returning a [GIOA]
func Eitherize6[GIOA ~func() ET.Either[error, R], F ~func(T1, T2, T3, T4, T5, T6) (R, error), T1, T2, T3, T4, T5, T6, R any](f F) func(T1, T2, T3, T4, T5, T6) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize6 converts a function with 6 parameters returning a tuple into a function with 6 parameters returning a [GIOA]
func Uneitherize6[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2, T3, T4, T5, T6) GIOA, T1, T2, T3, T4, T5, T6, R any](f GTA) func(T1, T2, T3, T4, T5, T6) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT6 converts 6 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple6[T1, T2, T3, T4, T5, T6]]]
func SequenceT6[
	G_TUPLE6 ~func() ET.Either[E, T.Tuple6[T1, T2, T3, T4, T5, T6]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	E, T1, T2, T3, T4, T5, T6 any](
	t1 G_T1,
	t2 G_T2,
	t3 G_T3,
	t4 G_T4,
	t5 G_T5,
	t6 G_T6,
) G_TUPLE6 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE6)
}

// SequenceTuple6 converts a [T.Tuple6[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple6[T1, T2, T3, T4, T5, T6]]]
func SequenceTuple6[
	G_TUPLE6 ~func() ET.Either[E, T.Tuple6[T1, T2, T3, T4, T5, T6]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	E, T1, T2, T3, T4, T5, T6 any](t T.Tuple6[G_T1, G_T2, G_T3, G_T4, G_T5, G_T6]) G_TUPLE6 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE6)
}

// TraverseTuple6 converts a [T.Tuple6[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple6[T1, T2, T3, T4, T5, T6]]]
func TraverseTuple6[
	G_TUPLE6 ~func() ET.Either[E, T.Tuple6[T1, T2, T3, T4, T5, T6]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	F3 ~func(A3) G_T3,
	F4 ~func(A4) G_T4,
	F5 ~func(A5) G_T5,
	F6 ~func(A6) G_T6,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	E, A1, A2, A3, A4, A5, A6, T1, T2, T3, T4, T5, T6 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6) func(T.Tuple6[A1, A2, A3, A4, A5, A6]) G_TUPLE6 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize7 converts a function with 7 parameters returning a tuple into a function with 7 parameters returning a [GIOA]
func Eitherize7[GIOA ~func() ET.Either[error, R], F ~func(T1, T2, T3, T4, T5, T6, T7) (R, error), T1, T2, T3, T4, T5, T6, T7, R any](f F) func(T1, T2, T3, T4, T5, T6, T7) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize7 converts a function with 7 parameters returning a tuple into a function with 7 parameters returning a [GIOA]
func Uneitherize7[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2, T3, T4, T5, T6, T7) GIOA, T1, T2, T3, T4, T5, T6, T7, R any](f GTA) func(T1, T2, T3, T4, T5, T6, T7) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT7 converts 7 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple7[T1, T2, T3, T4, T5, T6, T7]]]
func SequenceT7[
	G_TUPLE7 ~func() ET.Either[E, T.Tuple7[T1, T2, T3, T4, T5, T6, T7]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	E, T1, T2, T3, T4, T5, T6, T7 any](
	t1 G_T1,
	t2 G_T2,
	t3 G_T3,
	t4 G_T4,
	t5 G_T5,
	t6 G_T6,
	t7 G_T7,
) G_TUPLE7 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE7)
}

// SequenceTuple7 converts a [T.Tuple7[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple7[T1, T2, T3, T4, T5, T6, T7]]]
func SequenceTuple7[
	G_TUPLE7 ~func() ET.Either[E, T.Tuple7[T1, T2, T3, T4, T5, T6, T7]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	E, T1, T2, T3, T4, T5, T6, T7 any](t T.Tuple7[G_T1, G_T2, G_T3, G_T4, G_T5, G_T6, G_T7]) G_TUPLE7 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE7)
}

// TraverseTuple7 converts a [T.Tuple7[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple7[T1, T2, T3, T4, T5, T6, T7]]]
func TraverseTuple7[
	G_TUPLE7 ~func() ET.Either[E, T.Tuple7[T1, T2, T3, T4, T5, T6, T7]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	F3 ~func(A3) G_T3,
	F4 ~func(A4) G_T4,
	F5 ~func(A5) G_T5,
	F6 ~func(A6) G_T6,
	F7 ~func(A7) G_T7,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	E, A1, A2, A3, A4, A5, A6, A7, T1, T2, T3, T4, T5, T6, T7 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6, f7 F7) func(T.Tuple7[A1, A2, A3, A4, A5, A6, A7]) G_TUPLE7 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize8 converts a function with 8 parameters returning a tuple into a function with 8 parameters returning a [GIOA]
func Eitherize8[GIOA ~func() ET.Either[error, R], F ~func(T1, T2, T3, T4, T5, T6, T7, T8) (R, error), T1, T2, T3, T4, T5, T6, T7, T8, R any](f F) func(T1, T2, T3, T4, T5, T6, T7, T8) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize8 converts a function with 8 parameters returning a tuple into a function with 8 parameters returning a [GIOA]
func Uneitherize8[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2, T3, T4, T5, T6, T7, T8) GIOA, T1, T2, T3, T4, T5, T6, T7, T8, R any](f GTA) func(T1, T2, T3, T4, T5, T6, T7, T8) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT8 converts 8 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]]]
func SequenceT8[
	G_TUPLE8 ~func() ET.Either[E, T.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	E, T1, T2, T3, T4, T5, T6, T7, T8 any](
	t1 G_T1,
	t2 G_T2,
	t3 G_T3,
	t4 G_T4,
	t5 G_T5,
	t6 G_T6,
	t7 G_T7,
	t8 G_T8,
) G_TUPLE8 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE8)
}

// SequenceTuple8 converts a [T.Tuple8[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]]]
func SequenceTuple8[
	G_TUPLE8 ~func() ET.Either[E, T.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	E, T1, T2, T3, T4, T5, T6, T7, T8 any](t T.Tuple8[G_T1, G_T2, G_T3, G_T4, G_T5, G_T6, G_T7, G_T8]) G_TUPLE8 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE8)
}

// TraverseTuple8 converts a [T.Tuple8[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]]]
func TraverseTuple8[
	G_TUPLE8 ~func() ET.Either[E, T.Tuple8[T1, T2, T3, T4, T5, T6, T7, T8]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	F3 ~func(A3) G_T3,
	F4 ~func(A4) G_T4,
	F5 ~func(A5) G_T5,
	F6 ~func(A6) G_T6,
	F7 ~func(A7) G_T7,
	F8 ~func(A8) G_T8,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	E, A1, A2, A3, A4, A5, A6, A7, A8, T1, T2, T3, T4, T5, T6, T7, T8 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6, f7 F7, f8 F8) func(T.Tuple8[A1, A2, A3, A4, A5, A6, A7, A8]) G_TUPLE8 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize9 converts a function with 9 parameters returning a tuple into a function with 9 parameters returning a [GIOA]
func Eitherize9[GIOA ~func() ET.Either[error, R], F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) (R, error), T1, T2, T3, T4, T5, T6, T7, T8, T9, R any](f F) func(T1, T2, T3, T4, T5, T6, T7, T8, T9) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize9 converts a function with 9 parameters returning a tuple into a function with 9 parameters returning a [GIOA]
func Uneitherize9[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9) GIOA, T1, T2, T3, T4, T5, T6, T7, T8, T9, R any](f GTA) func(T1, T2, T3, T4, T5, T6, T7, T8, T9) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT9 converts 9 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]]]
func SequenceT9[
	G_TUPLE9 ~func() ET.Either[E, T.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	G_T9 ~func() ET.Either[E, T9],
	E, T1, T2, T3, T4, T5, T6, T7, T8, T9 any](
	t1 G_T1,
	t2 G_T2,
	t3 G_T3,
	t4 G_T4,
	t5 G_T5,
	t6 G_T6,
	t7 G_T7,
	t8 G_T8,
	t9 G_T9,
) G_TUPLE9 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE9)
}

// SequenceTuple9 converts a [T.Tuple9[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]]]
func SequenceTuple9[
	G_TUPLE9 ~func() ET.Either[E, T.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	G_T9 ~func() ET.Either[E, T9],
	E, T1, T2, T3, T4, T5, T6, T7, T8, T9 any](t T.Tuple9[G_T1, G_T2, G_T3, G_T4, G_T5, G_T6, G_T7, G_T8, G_T9]) G_TUPLE9 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE9)
}

// TraverseTuple9 converts a [T.Tuple9[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]]]
func TraverseTuple9[
	G_TUPLE9 ~func() ET.Either[E, T.Tuple9[T1, T2, T3, T4, T5, T6, T7, T8, T9]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	F3 ~func(A3) G_T3,
	F4 ~func(A4) G_T4,
	F5 ~func(A5) G_T5,
	F6 ~func(A6) G_T6,
	F7 ~func(A7) G_T7,
	F8 ~func(A8) G_T8,
	F9 ~func(A9) G_T9,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	G_T9 ~func() ET.Either[E, T9],
	E, A1, A2, A3, A4, A5, A6, A7, A8, A9, T1, T2, T3, T4, T5, T6, T7, T8, T9 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6, f7 F7, f8 F8, f9 F9) func(T.Tuple9[A1, A2, A3, A4, A5, A6, A7, A8, A9]) G_TUPLE9 {
	_ = "STUB: not implemented"
	return nil
}

// Eitherize10 converts a function with 10 parameters returning a tuple into a function with 10 parameters returning a [GIOA]
func Eitherize10[GIOA ~func() ET.Either[error, R], F ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) (R, error), T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any](f F) func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) GIOA {
	_ = "STUB: not implemented"
	return nil
}

// Uneitherize10 converts a function with 10 parameters returning a tuple into a function with 10 parameters returning a [GIOA]
func Uneitherize10[GIOA ~func() ET.Either[error, R], GTA ~func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) GIOA, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, R any](f GTA) func(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10) (R, error) {
	_ = "STUB: not implemented"
	return nil
}

// SequenceT10 converts 10 [func() ET.Either[E, T]] into a [func() ET.Either[E, T.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]]]
func SequenceT10[
	G_TUPLE10 ~func() ET.Either[E, T.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	G_T9 ~func() ET.Either[E, T9],
	G_T10 ~func() ET.Either[E, T10],
	E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any](
	t1 G_T1,
	t2 G_T2,
	t3 G_T3,
	t4 G_T4,
	t5 G_T5,
	t6 G_T6,
	t7 G_T7,
	t8 G_T8,
	t9 G_T9,
	t10 G_T10,
) G_TUPLE10 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE10)
}

// SequenceTuple10 converts a [T.Tuple10[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]]]
func SequenceTuple10[
	G_TUPLE10 ~func() ET.Either[E, T.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]],
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	G_T9 ~func() ET.Either[E, T9],
	G_T10 ~func() ET.Either[E, T10],
	E, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any](t T.Tuple10[G_T1, G_T2, G_T3, G_T4, G_T5, G_T6, G_T7, G_T8, G_T9, G_T10]) G_TUPLE10 {
	_ = "STUB: not implemented"
	return *new(G_TUPLE10)
}

// TraverseTuple10 converts a [T.Tuple10[func() ET.Either[E, T]]] into a [func() ET.Either[E, T.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]]]
func TraverseTuple10[
	G_TUPLE10 ~func() ET.Either[E, T.Tuple10[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10]],
	F1 ~func(A1) G_T1,
	F2 ~func(A2) G_T2,
	F3 ~func(A3) G_T3,
	F4 ~func(A4) G_T4,
	F5 ~func(A5) G_T5,
	F6 ~func(A6) G_T6,
	F7 ~func(A7) G_T7,
	F8 ~func(A8) G_T8,
	F9 ~func(A9) G_T9,
	F10 ~func(A10) G_T10,
	G_T1 ~func() ET.Either[E, T1],
	G_T2 ~func() ET.Either[E, T2],
	G_T3 ~func() ET.Either[E, T3],
	G_T4 ~func() ET.Either[E, T4],
	G_T5 ~func() ET.Either[E, T5],
	G_T6 ~func() ET.Either[E, T6],
	G_T7 ~func() ET.Either[E, T7],
	G_T8 ~func() ET.Either[E, T8],
	G_T9 ~func() ET.Either[E, T9],
	G_T10 ~func() ET.Either[E, T10],
	E, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 any](f1 F1, f2 F2, f3 F3, f4 F4, f5 F5, f6 F6, f7 F7, f8 F8, f9 F9, f10 F10) func(T.Tuple10[A1, A2, A3, A4, A5, A6, A7, A8, A9, A10]) G_TUPLE10 {
	_ = "STUB: not implemented"
	return nil
}
